baseURL: "https://nocsaren.netlify.app"
languageCode: "en-us"
title: "Can Serdar"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-MSGRVGZ52P

markup:
  goldmark:
    renderer:
      unsafe: true


    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "About & Portfolio"
  description: Lorem ipsum dolor sit amet consectetur adipisicing elit. 
  #staticPath: "/exampleSite/static/"  # The path to serve the static files from
  favicon: "/images/android-chrome-512x512.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "About & Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Can"
    subtitle: "I extract meaning from data"
    content: "lorem ipsum"
    image: /images/hero.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: /images/serdar_burak_can.pdf
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/nocsaren
        - icon: fab fa-twitter
          url: https://twitter.com/B_Can_Serdar

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/hero.jpg"
    content: |-
      I am a data scientist
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "lorem ipsum"
        - "lorem ipsum"
        - "lorem ipsum"
        - "lorem ipsum"
        - "lorem ipsum"
        - "lorem ipsum"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Researcher"
        company: "Ankara University"
        companyUrl: "https://www.ankara.edu.tr"
        date: "Sep 2014 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "lorem ipsum"

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Doctor of Philosopy"
        school:
          name: "Ankara University"
          url: "https://www.ankara.edu.tr"
        date: "2017 - present"
        GPA: "4.0 out of 4.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Master of Philosopy"
        school:
          name: "Ankara University"
          url: "https://www.ankara.edu.tr"
        date: "2014 - 2017"
        GPA: "3.8 out of 4.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Philosophy"
        school:
          name: "Hacettepe University"
          url: "https://www.hacettepe.edu.tr"
        date: "2008 - 2013"
        GPA: "3.9 out of 4.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
          - Lorem ipsum dolor sit amet consectetur adipisicing elit. 

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Collatz Conjecture
        content: Some Calculations and Visualizations on Collatz Conjecture 2:5000
        image: /images/projects/collatz.png
        featured:
          name: Go
          link: https://nocsaren.shinyapps.io/collatz-conjecture/
        badges:
          - "R"
          - "Shiny"
        links:
          - icon: fab fa-github
            url: https://github.com/nocsaren/collatz-conjecture

      - title: News Battles
        content: A small web app to compare news coverages of words.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://nocsaren.shinyapps.io/news-battles/
        badges:
          - "R"
          - "Shiny"
          - "API"
        links:
          - icon: fab fa-github
            url: https://github.com/nocsaren/news-battles

      - title: TBA
        content: TBA.
        image: /images/projects/profile2.jpg
        featured:
          name: TBA
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/nocsaren

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: can_serdar@msn.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
